name: compile assets 

on:
  workflow_call:

jobs:
  compile:
    runs-on: ubuntu-latest 
  
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 16 
      
      - name: Install NPM dependencies
        run: npm ci

      - name: Compile assets 
        run: npm run build 
      
      - name: Commit compiled files 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build: compile assets' 
          file_pattern: public/
